name: textris # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.57' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Text version of the classic falling blocks game
description: |
   Tetris, video game created by Russian designer Alexey Pajitnov in 1985 that allows players to rotate falling blocks strategically to clear levels. Pajitnov claimed he created the name of the game by combining the Greek prefix tetra, which refers to the four squares contained in each block, with the word tennis.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  tetris_icon.png
title: Vitris

apps:
  tetris:
    command: tetris
parts:
  tetris:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      tetris: build/
      tetris.1: man/man1/

architectures:
  - build-on: amd64

